[package]
name = "cuneos"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
rand = { version = "0.8", features = ["std_rng"] }
x25519-dalek = "2.0"